### ISSUE TITLE
raw Seurat/loom files?

### ISSUE THREAD

**Issue by mjstrumillo** [vilasmenon/Microglia_Olah_et_al_2020#1]
Hi, is it possible to obtain Seurat objects/loom/h5ad, anything processed from the fastq files? I cannot find anything more processed than fastqs on synapse?

**Comment by vilasmenon** [comment]
Hi there  - Supplementary Data 14 has the counts table and Supplemental Data 15 (both available directly in this repository). They are also both available directly from the paper. Additional formats (Seurat rds or AnnData h5ad) are available through the cellxgene repository: https://cellxgene.cziscience.com/collections/fcb3d1c1-03d2-41ac-8229-458e072b7a1c

**Comment by mjstrumillo** [comment]
Thank you! couldnt find the cellxgene info, thank you for the link!
