### ISSUE TITLE
visualize the data

### ISSUE THREAD

**Issue by tanyutingtyt** [vilasmenon/Microglia_Olah_et_al_2020#2]
Hi! How did you visualize the data as Fig.2b? I can't generate the tsne plot as you presented in the paper. The clusters are not well seperated in my plot.  Could you please upload the tsne coordinates?

**Comment by vilasmenon** [comment]
The t-SNE coordinates are available on cellxgene, here: https://cellxgene.cziscience.com/collections/fcb3d1c1-03d2-41ac-8229-458e072b7a1c
In the rds object, they can be found under object@reductions$tsne@cell.embeddings

**Comment by tanyutingtyt** [comment]
> The t-SNE coordinates are available on cellxgene, here: https://cellxgene.cziscience.com/collections/fcb3d1c1-03d2-41ac-8229-458e072b7a1c In the rds object, they can be found under object@reductions$[tsne@cell.embeddings](mailto:tsne@cell.embeddings)

Thank you for the link!

**Comment by tanyutingtyt** [comment]
Hi, Supplementary 16 can't be opened afer I download it. Do you have some suggestions? Thnaks!

**Comment by tanyutingtyt** [comment]
Hi, Supplementary 16 can't be opened afer I download it. Do you have any suggestions? Thanks!

**Comment by vilasmenon** [comment]
That's unfortunate - it looks like the file may have been corrupted on upload to the website. The table has z-scored values of log2-transformed TPM (transcripts per million) for each cell. This can be regenerated from the counts table using the following command in R, assuming the rows are the genes and the cells are in columns:
tpm_scaled=t(scale(t(log2((sweep(counts,2,colSums(counts),"/")*10^6)+1))))

**Comment by tanyutingtyt** [comment]
Thank you. Already generated the z-score.
